# SAI Dashboard - Production Override Configuration
# Use with: docker-compose -f docker-compose.yml -f docker-compose.production.yml up -d
# This file overrides settings for SSH tunnel deployment architecture

version: '3.8'

services:
  # =================================================================
  # SAI Dashboard Backend API - Production Settings
  # =================================================================
  sai-dashboard-api:
    # Bind to localhost only for SSH tunnel
    ports:
      - "127.0.0.1:${API_PORT:-3001}:3001"
    
    environment:
      # Production environment
      - NODE_ENV=production
      - LOG_LEVEL=warn
      - LOG_FORMAT=json
      
      # Database connection (direct to localhost, no Docker networking)
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@host.docker.internal:${DB_PORT}/${DB_NAME}
      
      # Base path for subpath deployment
      - BASE_PATH=/dashboard
      - API_BASE_PATH=/dashboard/api
      
      # Security (production values)
      - ENFORCE_HTTPS=true
      - TRUST_PROXY=true
      - CORS_ORIGIN=https://n8n.altermundi.net
      
      # Session configuration
      - SESSION_DURATION=86400
      - SESSION_SECRET=${SESSION_SECRET}
      
      # Rate limiting (production values)
      - RATE_LIMIT_MAX_REQUESTS=60
      - LOGIN_RATE_LIMIT_MAX=5
      
      # Filesystem cache (no Redis in production initially)
      - CACHE_PATH=/cache
      - ENABLE_THUMBNAIL_GENERATION=true
      - THUMBNAIL_SIZE=200
      - THUMBNAIL_QUALITY=70
    
    volumes:
      # Mount filesystem cache
      - /mnt/raid1/n8n/backup/images:/cache:rw
      
    # No Redis dependency in production
    depends_on: []
    
    # Production health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    
    # Restart policy
    restart: unless-stopped
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=sai-dashboard-api"

  # =================================================================
  # SAI Dashboard Frontend - Production Settings
  # =================================================================
  sai-dashboard-ui:
    # Bind to localhost only for SSH tunnel
    ports:
      - "127.0.0.1:${FRONTEND_PORT:-3000}:80"
    
    build:
      args:
        # Production build arguments
        - VITE_API_URL=https://n8n.altermundi.net/dashboard/api
        - VITE_BASE_PATH=/dashboard/
        - VITE_VERSION=${VERSION:-1.0.0}
    
    environment:
      - NODE_ENV=production
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    
    # No dependency on API in production (separate services)
    depends_on: []
    
    # Production health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/dashboard/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    
    # Restart policy
    restart: unless-stopped
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=sai-dashboard-ui"

  # =================================================================
  # Redis Cache - Disabled in Production (using filesystem cache)
  # =================================================================
  # Uncomment when ready to add Redis caching layer
  # sai-dashboard-redis:
  #   profiles:
  #     - redis
  #   ports:
  #     - "127.0.0.1:${REDIS_PORT:-6379}:6379"

# =================================================================
# Network Configuration - Production
# =================================================================
networks:
  default:
    name: sai_dashboard_network_prod
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1

# =================================================================
# Volume Configuration - Production
# =================================================================
volumes:
  # No additional volumes needed - using host filesystem for cache
  # Redis volume disabled until Redis is enabled
  # sai_redis_data:
  #   name: sai_dashboard_redis_data_prod
  #   driver: local